"""
Django settings for rest_api_example project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zdolq4suhu)!oq=6&z28dj*l4xkd*75fr!g*gxu@v1396^b-bt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "resources.snippets",
    "resources.users",
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'rest_api_example.urls'

REST_FRAMEWORK = {
  'PAGE_SIZE': 10,
  'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
  'DEFAULT_RENDERER_CLASSES': (
        'rest_api_example.custome_renderer.ApiV1',
        'rest_api_example.custome_renderer.ApiV2',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    )
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# LOGGING = {
#   'version': 1,
#   'disable_existing_loggers': False,
#   'formatters': {
#       'verbose': {
#           'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#           'datefmt' : "%d/%b/%Y %H:%M:%S"
#       },
#       'simple': {
#           'format': '%(levelname)s %(message)s'
#       },
#   },
#   'handlers': {
#       'console': {
#         'level': 'DEBUG',
#         'class': 'logging.StreamHandler',
#         'formatter': 'simple'
#         },
#       'file': {
#           'level': 'DEBUG',
#           'class': 'logging.FileHandler',
#           'filename': '.log',
#           'formatter': 'verbose'
#       },
#   },
#   'loggers': {
#       'django': {
#           'handlers':['file'],
#           'propagate': True,
#           'level':'DEBUG',
#       },
#       'rest_api_example': {
#           'handlers': ['file'],
#           'level': 'DEBUG',
#       },
#   }
# }
# if DEBUG:
#     # make all loggers use the console.
#     for logger in LOGGING['loggers']:
#         LOGGING['loggers'][logger]['handlers'] = ['console']


WSGI_APPLICATION = 'rest_api_example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'example_api',
        "USER" : "postgres",
        # "PASSWORD" : "testtest",
        "PORT" : "5432"
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
